"""create manufacturing foundation

Revision ID: 20260820_0011
Revises: 20260820_0010
Create Date: 2026-08-20 22:10:19.917657
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260820_0011"
down_revision: str | None = "20260820_0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manufacturing_recipes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("normalized_code", sa.String(length=80), nullable=False),
        sa.Column("name_ar", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("scrap_product_id", sa.Uuid(), nullable=False),
        sa.Column("suggested_scrap_per_batch", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "suggested_scrap_per_batch >= 0",
            name=op.f("ck_manufacturing_recipes_scrap_nonnegative"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_manufacturing_recipes_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_manufacturing_recipes_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scrap_product_id"],
            ["products.id"],
            name=op.f("fk_manufacturing_recipes_scrap_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_recipes")),
        sa.UniqueConstraint(
            "normalized_code", name=op.f("uq_manufacturing_recipes_normalized_code")
        ),
        sa.UniqueConstraint(
            "normalized_name", name=op.f("uq_manufacturing_recipes_normalized_name")
        ),
        sa.UniqueConstraint(
            "scrap_product_id", name=op.f("uq_manufacturing_recipes_scrap_product_id")
        ),
    )
    op.create_index(
        "ix_manufacturing_recipes_active",
        "manufacturing_recipes",
        ["is_active", "normalized_code"],
        unique=False,
    )
    op.create_table(
        "manufacturing_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=40), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("order_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_batches", sa.Integer(), nullable=False),
        sa.Column("issued_batches", sa.Integer(), nullable=False),
        sa.Column("actual_batches", sa.Integer(), nullable=False),
        sa.Column("target_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("planned_input_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("returned_scrap_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("material_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("finished_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("weight_variance_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("create_idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("create_request_hash", sa.String(length=64), nullable=False),
        sa.Column("start_idempotency_key", sa.String(length=120), nullable=True),
        sa.Column("start_request_hash", sa.String(length=64), nullable=True),
        sa.Column("completion_idempotency_key", sa.String(length=120), nullable=True),
        sa.Column("completion_request_hash", sa.String(length=64), nullable=True),
        sa.Column("cancellation_idempotency_key", sa.String(length=120), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("started_by_id", sa.Uuid(), nullable=True),
        sa.Column("completed_by_id", sa.Uuid(), nullable=True),
        sa.Column("cancelled_by_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'in_progress', 'completed', 'cancelled')",
            name=op.f("ck_manufacturing_orders_status_valid"),
        ),
        sa.CheckConstraint(
            "actual_batches >= 0", name=op.f("ck_manufacturing_orders_actual_batches_nonnegative")
        ),
        sa.CheckConstraint(
            "finished_cost >= 0", name=op.f("ck_manufacturing_orders_finished_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "issued_batches >= 0", name=op.f("ck_manufacturing_orders_issued_batches_nonnegative")
        ),
        sa.CheckConstraint(
            "material_cost >= 0", name=op.f("ck_manufacturing_orders_material_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "planned_batches > 0", name=op.f("ck_manufacturing_orders_planned_batches_positive")
        ),
        sa.CheckConstraint(
            "planned_input_weight_kg > 0",
            name=op.f("ck_manufacturing_orders_planned_input_weight_positive"),
        ),
        sa.CheckConstraint(
            "target_weight_kg > 0", name=op.f("ck_manufacturing_orders_target_weight_positive")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_manufacturing_orders_version_positive")),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"],
            ["users.id"],
            name=op.f("fk_manufacturing_orders_cancelled_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_id"],
            ["users.id"],
            name=op.f("fk_manufacturing_orders_completed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_manufacturing_orders_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["manufacturing_recipes.id"],
            name=op.f("fk_manufacturing_orders_recipe_id_manufacturing_recipes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["started_by_id"],
            ["users.id"],
            name=op.f("fk_manufacturing_orders_started_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_manufacturing_orders_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_orders")),
        sa.UniqueConstraint(
            "cancellation_idempotency_key",
            name=op.f("uq_manufacturing_orders_cancellation_idempotency_key"),
        ),
        sa.UniqueConstraint(
            "completion_idempotency_key",
            name=op.f("uq_manufacturing_orders_completion_idempotency_key"),
        ),
        sa.UniqueConstraint(
            "create_idempotency_key", name=op.f("uq_manufacturing_orders_create_idempotency_key")
        ),
        sa.UniqueConstraint("order_number", name=op.f("uq_manufacturing_orders_order_number")),
        sa.UniqueConstraint(
            "start_idempotency_key", name=op.f("uq_manufacturing_orders_start_idempotency_key")
        ),
    )
    op.create_index(
        "ix_manufacturing_orders_recipe_status",
        "manufacturing_orders",
        ["recipe_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_manufacturing_orders_status_date",
        "manufacturing_orders",
        ["status", "order_date"],
        unique=False,
    )
    op.create_table(
        "manufacturing_recipe_components",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_per_batch", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_order > 0",
            name=op.f("ck_manufacturing_recipe_components_display_order_positive"),
        ),
        sa.CheckConstraint(
            "quantity_per_batch > 0",
            name=op.f("ck_manufacturing_recipe_components_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_manufacturing_recipe_components_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["manufacturing_recipes.id"],
            name=op.f("fk_manufacturing_recipe_components_recipe_id_manufacturing_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_recipe_components")),
        sa.UniqueConstraint(
            "recipe_id", "product_id", name=op.f("uq_manufacturing_recipe_components_recipe_id")
        ),
    )
    op.create_index(
        "ix_manufacturing_recipe_components_recipe",
        "manufacturing_recipe_components",
        ["recipe_id", "display_order"],
        unique=False,
    )
    op.create_table(
        "manufacturing_recipe_outputs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_manufacturing_recipe_outputs_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["manufacturing_recipes.id"],
            name=op.f("fk_manufacturing_recipe_outputs_recipe_id_manufacturing_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_recipe_outputs")),
        sa.UniqueConstraint(
            "recipe_id", "product_id", name=op.f("uq_manufacturing_recipe_outputs_recipe_id")
        ),
    )
    op.create_index(
        "ix_manufacturing_recipe_outputs_product",
        "manufacturing_recipe_outputs",
        ["product_id", "recipe_id"],
        unique=False,
    )
    op.create_table(
        "manufacturing_completions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("manufacturing_order_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("actual_batches", sa.Integer(), nullable=False),
        sa.Column("full_batches", sa.Integer(), nullable=False),
        sa.Column("modified_batches", sa.Integer(), nullable=False),
        sa.Column("good_output_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("defective_output_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("actual_output_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("scrap_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("used_input_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("full_mix_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("modified_mix_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("total_material_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("average_input_cost_per_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("scrap_value", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("finished_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("cost_per_good_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("weight_variance_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("scrap_inventory_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("completed_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actual_batches > 0", name=op.f("ck_manufacturing_completions_actual_batches_positive")
        ),
        sa.CheckConstraint(
            "actual_output_weight_kg > 0",
            name=op.f("ck_manufacturing_completions_actual_output_weight_positive"),
        ),
        sa.CheckConstraint(
            "defective_output_quantity >= 0",
            name=op.f("ck_manufacturing_completions_defective_output_nonnegative"),
        ),
        sa.CheckConstraint(
            "finished_cost >= 0",
            name=op.f("ck_manufacturing_completions_finished_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "full_batches >= 0", name=op.f("ck_manufacturing_completions_full_batches_nonnegative")
        ),
        sa.CheckConstraint(
            "full_mix_cost >= 0",
            name=op.f("ck_manufacturing_completions_full_mix_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "good_output_quantity > 0",
            name=op.f("ck_manufacturing_completions_good_output_positive"),
        ),
        sa.CheckConstraint(
            "modified_batches >= 0",
            name=op.f("ck_manufacturing_completions_modified_batches_nonnegative"),
        ),
        sa.CheckConstraint(
            "modified_mix_cost >= 0",
            name=op.f("ck_manufacturing_completions_modified_mix_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "scrap_weight_kg >= 0",
            name=op.f("ck_manufacturing_completions_scrap_weight_nonnegative"),
        ),
        sa.CheckConstraint(
            "total_material_cost >= 0",
            name=op.f("ck_manufacturing_completions_total_material_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "used_input_weight_kg > 0",
            name=op.f("ck_manufacturing_completions_used_input_weight_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_id"],
            ["users.id"],
            name=op.f("fk_manufacturing_completions_completed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["manufacturing_order_id"],
            ["manufacturing_orders.id"],
            name=op.f("fk_manufacturing_completions_manufacturing_order_id_manufacturing_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scrap_inventory_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f(
                "fk_manufacturing_completions_scrap_inventory_transaction_id_inventory_transactions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_completions")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_manufacturing_completions_idempotency_key")
        ),
        sa.UniqueConstraint(
            "manufacturing_order_id",
            name=op.f("uq_manufacturing_completions_manufacturing_order_id"),
        ),
        sa.UniqueConstraint(
            "scrap_inventory_transaction_id",
            name=op.f("uq_manufacturing_completions_scrap_inventory_transaction_id"),
        ),
    )
    op.create_table(
        "manufacturing_order_materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("manufacturing_order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("component_kind", sa.String(length=16), nullable=False),
        sa.Column("quantity_per_batch", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("planned_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("issued_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("used_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("returned_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("issued_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("used_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("return_inventory_transaction_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "component_kind IN ('material', 'scrap')",
            name=op.f("ck_manufacturing_order_materials_kind_valid"),
        ),
        sa.CheckConstraint(
            "issued_cost >= 0",
            name=op.f("ck_manufacturing_order_materials_issued_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "issued_quantity >= 0",
            name=op.f("ck_manufacturing_order_materials_issued_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "planned_quantity >= 0",
            name=op.f("ck_manufacturing_order_materials_planned_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "quantity_per_batch > 0",
            name=op.f("ck_manufacturing_order_materials_quantity_per_batch_positive"),
        ),
        sa.CheckConstraint(
            "returned_quantity >= 0",
            name=op.f("ck_manufacturing_order_materials_returned_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "used_cost >= 0", name=op.f("ck_manufacturing_order_materials_used_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "used_quantity >= 0",
            name=op.f("ck_manufacturing_order_materials_used_quantity_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["manufacturing_order_id"],
            ["manufacturing_orders.id"],
            name=op.f(
                "fk_manufacturing_order_materials_manufacturing_order_id_manufacturing_orders"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_manufacturing_order_materials_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["return_inventory_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f(
                "fk_manufacturing_order_materials_return_inventory_transaction_id_inventory_transactions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_order_materials")),
        sa.UniqueConstraint(
            "manufacturing_order_id",
            "product_id",
            name=op.f("uq_manufacturing_order_materials_manufacturing_order_id"),
        ),
        sa.UniqueConstraint(
            "return_inventory_transaction_id",
            name=op.f("uq_manufacturing_order_materials_return_inventory_transaction_id"),
        ),
    )
    op.create_index(
        "ix_manufacturing_order_materials_order",
        "manufacturing_order_materials",
        ["manufacturing_order_id", "id"],
        unique=False,
    )
    op.create_table(
        "manufacturing_order_outputs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("manufacturing_order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("planned_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("standard_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("good_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("defective_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("actual_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("line_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("inventory_transaction_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actual_weight_kg >= 0",
            name=op.f("ck_manufacturing_order_outputs_actual_weight_nonnegative"),
        ),
        sa.CheckConstraint(
            "defective_quantity >= 0",
            name=op.f("ck_manufacturing_order_outputs_defective_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "good_quantity >= 0",
            name=op.f("ck_manufacturing_order_outputs_good_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "line_cost >= 0", name=op.f("ck_manufacturing_order_outputs_line_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "planned_quantity > 0",
            name=op.f("ck_manufacturing_order_outputs_planned_quantity_positive"),
        ),
        sa.CheckConstraint(
            "standard_weight_kg > 0",
            name=op.f("ck_manufacturing_order_outputs_standard_weight_positive"),
        ),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_manufacturing_order_outputs_unit_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f(
                "fk_manufacturing_order_outputs_inventory_transaction_id_inventory_transactions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["manufacturing_order_id"],
            ["manufacturing_orders.id"],
            name=op.f("fk_manufacturing_order_outputs_manufacturing_order_id_manufacturing_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_manufacturing_order_outputs_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_order_outputs")),
        sa.UniqueConstraint(
            "inventory_transaction_id",
            name=op.f("uq_manufacturing_order_outputs_inventory_transaction_id"),
        ),
        sa.UniqueConstraint(
            "manufacturing_order_id",
            "product_id",
            name=op.f("uq_manufacturing_order_outputs_manufacturing_order_id"),
        ),
    )
    op.create_index(
        "ix_manufacturing_order_outputs_order",
        "manufacturing_order_outputs",
        ["manufacturing_order_id", "id"],
        unique=False,
    )
    op.create_table(
        "manufacturing_completion_outputs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("completion_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("good_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("defective_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("actual_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("line_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("inventory_transaction_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actual_weight_kg >= 0",
            name=op.f("ck_manufacturing_completion_outputs_actual_weight_nonnegative"),
        ),
        sa.CheckConstraint(
            "defective_quantity >= 0",
            name=op.f("ck_manufacturing_completion_outputs_defective_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "good_quantity >= 0",
            name=op.f("ck_manufacturing_completion_outputs_good_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "line_cost >= 0", name=op.f("ck_manufacturing_completion_outputs_line_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_manufacturing_completion_outputs_unit_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["completion_id"],
            ["manufacturing_completions.id"],
            name=op.f(
                "fk_manufacturing_completion_outputs_completion_id_manufacturing_completions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f(
                "fk_manufacturing_completion_outputs_inventory_transaction_id_inventory_transactions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_manufacturing_completion_outputs_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_completion_outputs")),
        sa.UniqueConstraint(
            "completion_id",
            "product_id",
            name=op.f("uq_manufacturing_completion_outputs_completion_id"),
        ),
        sa.UniqueConstraint(
            "inventory_transaction_id",
            name=op.f("uq_manufacturing_completion_outputs_inventory_transaction_id"),
        ),
    )
    op.create_table(
        "manufacturing_material_issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_material_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_transaction_id", sa.Uuid(), nullable=False),
        sa.Column("reversal_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("issue_kind", sa.String(length=16), nullable=False),
        sa.Column("batch_count", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "issue_kind IN ('initial', 'additional')",
            name=op.f("ck_manufacturing_material_issues_kind_valid"),
        ),
        sa.CheckConstraint(
            "batch_count > 0", name=op.f("ck_manufacturing_material_issues_batch_count_positive")
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_manufacturing_material_issues_quantity_positive")
        ),
        sa.CheckConstraint(
            "total_cost >= 0", name=op.f("ck_manufacturing_material_issues_total_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "weight_kg >= 0", name=op.f("ck_manufacturing_material_issues_weight_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f(
                "fk_manufacturing_material_issues_inventory_transaction_id_inventory_transactions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_material_id"],
            ["manufacturing_order_materials.id"],
            name=op.f(
                "fk_manufacturing_material_issues_order_material_id_manufacturing_order_materials"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f(
                "fk_manufacturing_material_issues_reversal_transaction_id_inventory_transactions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_material_issues")),
        sa.UniqueConstraint(
            "inventory_transaction_id",
            name=op.f("uq_manufacturing_material_issues_inventory_transaction_id"),
        ),
        sa.UniqueConstraint(
            "reversal_transaction_id",
            name=op.f("uq_manufacturing_material_issues_reversal_transaction_id"),
        ),
    )
    op.create_index(
        "ix_manufacturing_material_issues_material",
        "manufacturing_material_issues",
        ["order_material_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "manufacturing_mix_adjustments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("completion_id", sa.Uuid(), nullable=False),
        sa.Column("excluded_product_id", sa.Uuid(), nullable=False),
        sa.Column("batch_count", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("cost_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "batch_count > 0", name=op.f("ck_manufacturing_mix_adjustments_batch_count_positive")
        ),
        sa.CheckConstraint(
            "cost_amount >= 0", name=op.f("ck_manufacturing_mix_adjustments_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["completion_id"],
            ["manufacturing_completions.id"],
            name=op.f("fk_manufacturing_mix_adjustments_completion_id_manufacturing_completions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["excluded_product_id"],
            ["products.id"],
            name=op.f("fk_manufacturing_mix_adjustments_excluded_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_mix_adjustments")),
    )
    op.create_index(
        "ix_manufacturing_mix_adjustments_completion",
        "manufacturing_mix_adjustments",
        ["completion_id", "id"],
        unique=False,
    )
    op.create_table(
        "manufacturing_mix_adjustment_materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("adjustment_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("actual_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actual_quantity >= 0",
            name=op.f("ck_manufacturing_mix_adjustment_materials_actual_quantity_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["manufacturing_mix_adjustments.id"],
            name=op.f(
                "fk_manufacturing_mix_adjustment_materials_adjustment_id_manufacturing_mix_adjustments"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_manufacturing_mix_adjustment_materials_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturing_mix_adjustment_materials")),
        sa.UniqueConstraint(
            "adjustment_id",
            "product_id",
            name=op.f("uq_manufacturing_mix_adjustment_materials_adjustment_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manufacturing_mix_adjustment_materials")
    op.drop_index(
        "ix_manufacturing_mix_adjustments_completion", table_name="manufacturing_mix_adjustments"
    )
    op.drop_table("manufacturing_mix_adjustments")
    op.drop_index(
        "ix_manufacturing_material_issues_material", table_name="manufacturing_material_issues"
    )
    op.drop_table("manufacturing_material_issues")
    op.drop_table("manufacturing_completion_outputs")
    op.drop_index("ix_manufacturing_order_outputs_order", table_name="manufacturing_order_outputs")
    op.drop_table("manufacturing_order_outputs")
    op.drop_index(
        "ix_manufacturing_order_materials_order", table_name="manufacturing_order_materials"
    )
    op.drop_table("manufacturing_order_materials")
    op.drop_table("manufacturing_completions")
    op.drop_index(
        "ix_manufacturing_recipe_outputs_product", table_name="manufacturing_recipe_outputs"
    )
    op.drop_table("manufacturing_recipe_outputs")
    op.drop_index(
        "ix_manufacturing_recipe_components_recipe", table_name="manufacturing_recipe_components"
    )
    op.drop_table("manufacturing_recipe_components")
    op.drop_index("ix_manufacturing_orders_status_date", table_name="manufacturing_orders")
    op.drop_index("ix_manufacturing_orders_recipe_status", table_name="manufacturing_orders")
    op.drop_table("manufacturing_orders")
    op.drop_index("ix_manufacturing_recipes_active", table_name="manufacturing_recipes")
    op.drop_table("manufacturing_recipes")
    # ### end Alembic commands ###
