"""create purchasing foundation

Revision ID: 20260818_0008
Revises: 20260818_0007
Create Date: 2026-08-18 08:39:39.078328
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260818_0008"
down_revision: str | None = "20260818_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=40), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "order_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("total", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'partially_received', 'received', 'cancelled')",
            name=op.f("ck_purchase_orders_status_valid"),
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_purchase_orders_total_nonnegative")),
        sa.CheckConstraint("version > 0", name=op.f("ck_purchase_orders_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_purchase_orders_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["partners.id"],
            name=op.f("fk_purchase_orders_supplier_id_partners"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_purchase_orders_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_purchase_orders_order_number")),
    )
    op.create_index(
        "ix_purchase_orders_supplier_status",
        "purchase_orders",
        ["supplier_id", "status"],
        unique=False,
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("cost_basis", sa.String(length=16), nullable=False),
        sa.Column("ordered_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("ordered_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("additional_unit_cost", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("received_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("received_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cost_basis IN ('quantity', 'weight')",
            name=op.f("ck_purchase_order_lines_cost_basis_valid"),
        ),
        sa.CheckConstraint(
            "additional_unit_cost >= 0",
            name=op.f("ck_purchase_order_lines_additional_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "line_total >= 0", name=op.f("ck_purchase_order_lines_line_total_nonnegative")
        ),
        sa.CheckConstraint(
            "ordered_quantity > 0 OR ordered_weight_kg > 0",
            name=op.f("ck_purchase_order_lines_ordered_amount_positive"),
        ),
        sa.CheckConstraint(
            "ordered_quantity >= 0",
            name=op.f("ck_purchase_order_lines_ordered_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "ordered_weight_kg >= 0",
            name=op.f("ck_purchase_order_lines_ordered_weight_nonnegative"),
        ),
        sa.CheckConstraint(
            "received_quantity <= ordered_quantity",
            name=op.f("ck_purchase_order_lines_received_quantity_within_order"),
        ),
        sa.CheckConstraint(
            "received_quantity >= 0",
            name=op.f("ck_purchase_order_lines_received_quantity_nonnegative"),
        ),
        sa.CheckConstraint(
            "received_weight_kg <= ordered_weight_kg",
            name=op.f("ck_purchase_order_lines_received_weight_within_order"),
        ),
        sa.CheckConstraint(
            "received_weight_kg >= 0",
            name=op.f("ck_purchase_order_lines_received_weight_nonnegative"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_purchase_order_lines_unit_price_nonnegative")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_purchase_order_lines_version_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchase_order_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_order_lines_purchase_order_id_purchase_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
    )
    op.create_index(
        "ix_purchase_order_lines_order",
        "purchase_order_lines",
        ["purchase_order_id", "id"],
        unique=False,
    )
    op.create_table(
        "purchase_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_number", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("posted_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "posted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('posted', 'reversed')", name=op.f("ck_purchase_receipts_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["posted_by_id"],
            ["users.id"],
            name=op.f("fk_purchase_receipts_posted_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_receipts_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_receipts")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_purchase_receipts_idempotency_key")),
        sa.UniqueConstraint("receipt_number", name=op.f("uq_purchase_receipts_receipt_number")),
    )
    op.create_index(
        "ix_purchase_receipts_order",
        "purchase_receipts",
        ["purchase_order_id", "posted_at"],
        unique=False,
    )
    op.create_table(
        "supplier_invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=40), nullable=False),
        sa.Column("supplier_invoice_number", sa.String(length=80), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'posted', 'reversed')",
            name=op.f("ck_supplier_invoices_status_valid"),
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_supplier_invoices_total_nonnegative")),
        sa.CheckConstraint("version > 0", name=op.f("ck_supplier_invoices_version_positive")),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_supplier_invoices_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["partners.id"],
            name=op.f("fk_supplier_invoices_supplier_id_partners"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_invoices")),
        sa.UniqueConstraint("invoice_number", name=op.f("uq_supplier_invoices_invoice_number")),
        sa.UniqueConstraint(
            "purchase_order_id", name=op.f("uq_supplier_invoices_purchase_order_id")
        ),
        sa.UniqueConstraint(
            "supplier_id", "supplier_invoice_number", name=op.f("uq_supplier_invoices_supplier_id")
        ),
    )
    op.create_table(
        "purchase_receipt_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("purchase_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_line_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_transaction_id", sa.Uuid(), nullable=False),
        sa.Column("lot_number", sa.String(length=80), nullable=False),
        sa.Column("gross_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("gross_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("loss_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("loss_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("net_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("net_weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("capitalized_cost", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("inventory_unit_cost", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "capitalized_cost >= 0",
            name=op.f("ck_purchase_receipt_lines_capitalized_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "gross_quantity >= 0", name=op.f("ck_purchase_receipt_lines_gross_quantity_nonnegative")
        ),
        sa.CheckConstraint(
            "gross_weight_kg >= 0", name=op.f("ck_purchase_receipt_lines_gross_weight_nonnegative")
        ),
        sa.CheckConstraint(
            "inventory_unit_cost >= 0",
            name=op.f("ck_purchase_receipt_lines_inventory_unit_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "loss_quantity <= gross_quantity",
            name=op.f("ck_purchase_receipt_lines_loss_quantity_within_gross"),
        ),
        sa.CheckConstraint(
            "loss_quantity >= 0", name=op.f("ck_purchase_receipt_lines_loss_quantity_nonnegative")
        ),
        sa.CheckConstraint(
            "loss_weight_kg <= gross_weight_kg",
            name=op.f("ck_purchase_receipt_lines_loss_weight_within_gross"),
        ),
        sa.CheckConstraint(
            "loss_weight_kg >= 0", name=op.f("ck_purchase_receipt_lines_loss_weight_nonnegative")
        ),
        sa.CheckConstraint(
            "net_quantity >= 0", name=op.f("ck_purchase_receipt_lines_net_quantity_nonnegative")
        ),
        sa.CheckConstraint(
            "net_weight_kg >= 0", name=op.f("ck_purchase_receipt_lines_net_weight_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f("fk_purchase_receipt_lines_inventory_transaction_id_inventory_transactions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_line_id"],
            ["purchase_order_lines.id"],
            name=op.f("fk_purchase_receipt_lines_purchase_order_line_id_purchase_order_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_receipt_id"],
            ["purchase_receipts.id"],
            name=op.f("fk_purchase_receipt_lines_purchase_receipt_id_purchase_receipts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_receipt_lines")),
        sa.UniqueConstraint(
            "inventory_transaction_id",
            name=op.f("uq_purchase_receipt_lines_inventory_transaction_id"),
        ),
        sa.UniqueConstraint(
            "purchase_receipt_id",
            "purchase_order_line_id",
            name=op.f("uq_purchase_receipt_lines_purchase_receipt_id"),
        ),
    )
    op.execute(
        sa.text(
            "INSERT INTO document_sequences "
            "(document_type, prefix, next_value, padding, version) "
            "VALUES ('purchase_receipt', 'PR-', 1, 6, 1)"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM document_sequences WHERE document_type = 'purchase_receipt'"))
    op.drop_table("purchase_receipt_lines")
    op.drop_table("supplier_invoices")
    op.drop_index("ix_purchase_receipts_order", table_name="purchase_receipts")
    op.drop_table("purchase_receipts")
    op.drop_index("ix_purchase_order_lines_order", table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index("ix_purchase_orders_supplier_status", table_name="purchase_orders")
    op.drop_table("purchase_orders")
    # ### end Alembic commands ###
