"""create returns and refunds

Revision ID: 20260821_0012
Revises: 20260820_0011
Create Date: 2026-08-21 00:01:42.198019
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260821_0012"
down_revision: str | None = "20260820_0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_returns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("return_number", sa.String(length=40), nullable=False),
        sa.Column("return_type", sa.String(length=16), nullable=False),
        sa.Column("customer_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("partner_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column(
            "return_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("total", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("posted_by_id", sa.Uuid(), nullable=False),
        sa.Column("reversed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.Text(), nullable=False),
        sa.Column("reversal_idempotency_key", sa.String(length=120), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(return_type = 'sales' AND customer_invoice_id IS NOT NULL "
            "AND supplier_invoice_id IS NULL) OR "
            "(return_type = 'purchase' AND supplier_invoice_id IS NOT NULL "
            "AND customer_invoice_id IS NULL)",
            name=op.f("ck_invoice_returns_invoice_matches_return_type"),
        ),
        sa.CheckConstraint(
            "return_type IN ('sales','purchase')", name=op.f("ck_invoice_returns_return_type_valid")
        ),
        sa.CheckConstraint(
            "status IN ('posted','reversed')", name=op.f("ck_invoice_returns_status_valid")
        ),
        sa.CheckConstraint("total > 0", name=op.f("ck_invoice_returns_total_positive")),
        sa.CheckConstraint("version > 0", name=op.f("ck_invoice_returns_version_positive")),
        sa.ForeignKeyConstraint(
            ["customer_invoice_id"],
            ["customer_invoices.id"],
            name=op.f("fk_invoice_returns_customer_invoice_id_customer_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
            name=op.f("fk_invoice_returns_partner_id_partners"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["posted_by_id"],
            ["users.id"],
            name=op.f("fk_invoice_returns_posted_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_id"],
            ["users.id"],
            name=op.f("fk_invoice_returns_reversed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_invoice_id"],
            ["supplier_invoices.id"],
            name=op.f("fk_invoice_returns_supplier_invoice_id_supplier_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_invoice_returns_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_returns")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_invoice_returns_idempotency_key")),
        sa.UniqueConstraint("return_number", name=op.f("uq_invoice_returns_return_number")),
        sa.UniqueConstraint(
            "reversal_idempotency_key", name=op.f("uq_invoice_returns_reversal_idempotency_key")
        ),
    )
    op.create_index(
        "ix_invoice_returns_customer_invoice",
        "invoice_returns",
        ["customer_invoice_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_returns_partner_date",
        "invoice_returns",
        ["partner_id", "return_date"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_returns_supplier_invoice",
        "invoice_returns",
        ["supplier_invoice_id", "status"],
        unique=False,
    )
    op.create_table(
        "return_refunds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("refund_number", sa.String(length=40), nullable=False),
        sa.Column("refund_type", sa.String(length=24), nullable=False),
        sa.Column("customer_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("partner_id", sa.Uuid(), nullable=False),
        sa.Column("financial_account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "refund_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(length=24), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("posted_by_id", sa.Uuid(), nullable=False),
        sa.Column("reversed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.Text(), nullable=False),
        sa.Column("reversal_idempotency_key", sa.String(length=120), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(refund_type = 'customer_refund' AND customer_invoice_id IS NOT NULL "
            "AND supplier_invoice_id IS NULL) OR "
            "(refund_type = 'supplier_refund' AND supplier_invoice_id IS NOT NULL "
            "AND customer_invoice_id IS NULL)",
            name=op.f("ck_return_refunds_invoice_matches_refund_type"),
        ),
        sa.CheckConstraint(
            "payment_method IN ('cash','bank_transfer','cheque','wallet')",
            name=op.f("ck_return_refunds_payment_method_valid"),
        ),
        sa.CheckConstraint(
            "refund_type IN ('supplier_refund','customer_refund')",
            name=op.f("ck_return_refunds_refund_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('posted','reversed')", name=op.f("ck_return_refunds_status_valid")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_return_refunds_amount_positive")),
        sa.CheckConstraint("version > 0", name=op.f("ck_return_refunds_version_positive")),
        sa.ForeignKeyConstraint(
            ["customer_invoice_id"],
            ["customer_invoices.id"],
            name=op.f("fk_return_refunds_customer_invoice_id_customer_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["financial_account_id"],
            ["financial_accounts.id"],
            name=op.f("fk_return_refunds_financial_account_id_financial_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
            name=op.f("fk_return_refunds_partner_id_partners"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["posted_by_id"],
            ["users.id"],
            name=op.f("fk_return_refunds_posted_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_id"],
            ["users.id"],
            name=op.f("fk_return_refunds_reversed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_invoice_id"],
            ["supplier_invoices.id"],
            name=op.f("fk_return_refunds_supplier_invoice_id_supplier_invoices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_refunds")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_return_refunds_idempotency_key")),
        sa.UniqueConstraint("refund_number", name=op.f("uq_return_refunds_refund_number")),
        sa.UniqueConstraint(
            "reversal_idempotency_key", name=op.f("uq_return_refunds_reversal_idempotency_key")
        ),
    )
    op.create_index(
        "ix_return_refunds_account_date",
        "return_refunds",
        ["financial_account_id", "refund_date"],
        unique=False,
    )
    op.create_index(
        "ix_return_refunds_partner_date",
        "return_refunds",
        ["partner_id", "refund_date"],
        unique=False,
    )
    op.create_table(
        "invoice_return_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_return_id", sa.Uuid(), nullable=False),
        sa.Column("sales_order_line_id", sa.Uuid(), nullable=True),
        sa.Column("purchase_order_line_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_transaction_id", sa.Uuid(), nullable=False),
        sa.Column("reversal_inventory_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("cost_basis", sa.String(length=16), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("inventory_cost", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cost_basis IN ('quantity','weight')",
            name=op.f("ck_invoice_return_lines_cost_basis_valid"),
        ),
        sa.CheckConstraint(
            "(sales_order_line_id IS NOT NULL AND purchase_order_line_id IS NULL) OR "
            "(sales_order_line_id IS NULL AND purchase_order_line_id IS NOT NULL)",
            name=op.f("ck_invoice_return_lines_exactly_one_source_line"),
        ),
        sa.CheckConstraint(
            "inventory_cost >= 0", name=op.f("ck_invoice_return_lines_inventory_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "line_total >= 0", name=op.f("ck_invoice_return_lines_line_total_nonnegative")
        ),
        sa.CheckConstraint(
            "quantity > 0 OR weight_kg > 0", name=op.f("ck_invoice_return_lines_amount_positive")
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_invoice_return_lines_quantity_nonnegative")
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_invoice_return_lines_unit_price_nonnegative")
        ),
        sa.CheckConstraint(
            "weight_kg >= 0", name=op.f("ck_invoice_return_lines_weight_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f("fk_invoice_return_lines_inventory_transaction_id_inventory_transactions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_return_id"],
            ["invoice_returns.id"],
            name=op.f("fk_invoice_return_lines_invoice_return_id_invoice_returns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_invoice_return_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_line_id"],
            ["purchase_order_lines.id"],
            name=op.f("fk_invoice_return_lines_purchase_order_line_id_purchase_order_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_inventory_transaction_id"],
            ["inventory_transactions.id"],
            name=op.f(
                "fk_invoice_return_lines_reversal_inventory_transaction_id_inventory_transactions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_line_id"],
            ["sales_order_lines.id"],
            name=op.f("fk_invoice_return_lines_sales_order_line_id_sales_order_lines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_return_lines")),
        sa.UniqueConstraint(
            "inventory_transaction_id",
            name=op.f("uq_invoice_return_lines_inventory_transaction_id"),
        ),
        sa.UniqueConstraint(
            "invoice_return_id",
            "purchase_order_line_id",
            name="uq_invoice_return_lines_return_purchase_line",
        ),
        sa.UniqueConstraint(
            "invoice_return_id",
            "sales_order_line_id",
            name="uq_invoice_return_lines_return_sales_line",
        ),
        sa.UniqueConstraint(
            "reversal_inventory_transaction_id",
            name=op.f("uq_invoice_return_lines_reversal_inventory_transaction_id"),
        ),
    )
    op.create_index(
        "ix_invoice_return_lines_return",
        "invoice_return_lines",
        ["invoice_return_id", "id"],
        unique=False,
    )
    for document_type, prefix in (
        ("sales_return", "SR-"),
        ("purchase_return", "PR-"),
        ("customer_refund", "CRF-"),
        ("supplier_refund", "SRF-"),
    ):
        op.execute(
            sa.text(
                "INSERT INTO document_sequences "
                "(document_type, prefix, next_value, padding, version) "
                "SELECT :document_type, :prefix, 1, 6, 1 "
                "WHERE NOT EXISTS (SELECT 1 FROM document_sequences "
                "WHERE document_type = :document_type)"
            ).bindparams(document_type=document_type, prefix=prefix)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "DELETE FROM document_sequences WHERE document_type IN "
            "('sales_return','purchase_return','customer_refund','supplier_refund')"
        )
    )
    op.drop_index("ix_invoice_return_lines_return", table_name="invoice_return_lines")
    op.drop_table("invoice_return_lines")
    op.drop_index("ix_return_refunds_partner_date", table_name="return_refunds")
    op.drop_index("ix_return_refunds_account_date", table_name="return_refunds")
    op.drop_table("return_refunds")
    op.drop_index("ix_invoice_returns_supplier_invoice", table_name="invoice_returns")
    op.drop_index("ix_invoice_returns_partner_date", table_name="invoice_returns")
    op.drop_index("ix_invoice_returns_customer_invoice", table_name="invoice_returns")
    op.drop_table("invoice_returns")
    # ### end Alembic commands ###
